---

- name: VM test with outside network
  hosts: all
  gather_facts: true


- name: Install MongoDB on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Import the public key used by the package management system
      become: yes
      ansible.builtin.copy:
       content: '# This file was moved to /etc/other.conf'
       dest: /etc/mine.conf
