- name: VM test with outside network
  hosts: all
  gather_facts: true

  tasks:
  - name: Checking if machine can ping to google.com
    ansible.builtin.shell: echo {{ ansible_all_ipv4_addresses[1] }}
    register: displayfile
  - debug:
     msg: "{{ displayfile.stdout_lines }}"
