
- name: installing dependecies for epc
  become: yes
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - ninja-build
      - build-essential
      - flex 
      - bison 
      - git 
      - cmake 
      - libsctp-dev 
      - libgnutls28-dev 
      - libgcrypt-dev 
      - libssl-dev 
      - libidn11-dev 
      - libmongoc-dev 
      - libbson-dev 
      - libyaml-dev 
      - libnghttp2-dev 
      - libmicrohttpd-dev 
      - libcurl4-gnutls-dev 
      - libnghttp2-dev 
      - libtins-dev 
      - libtalloc-dev 
      - meson
    state: latest
