- name: Example clone of a single branch
  git:
    repo: https://github.com/shopon16/open5gs.git
    dest: "{{source_dir}}/open5gs"
    clone: yes
    update: yes
  register: mygit
- name: printing
  debug:
    msg: "fsdf {{mygit.before}} and {{mygit.after}}"

- name: Get stats of the FS object
  become: yes
  ansible.builtin.stat:
    path: "{{source_dir}}/open5gs/build/"
  register: p
- name: Building open5gs from Source Code
  become: yes
  ansible.builtin.shell: cd {{source_dir}}/open5gs && meson build --bindir {{exec_path}} --prefix=/ && ninja -C build && cd build && ninja install
  register: ass
  when: p.stat.isdir is defined == false
- debug:
    msg: "{{ass}}"

- name: Re-Compiling open5gs
  become: yes
  ansible.builtin.shell: cd {{source_dir}}/open5gs && ninja -C build && cd build && ninja install
  register: ass
  when: mygit.before != mygit.after
- debug:
    msg: "{{ass}}"
