- name: Get stats of the FS object
  ansible.builtin.stat:
    path: /home/vagrant/open5gs/build/
  register: p
- name: Building open5gs from Source Code
  ansible.builtin.shell: cd /home/vagrant/open5gs && meson build --prefix=/home/vagrant/open5gs/install && ninja -C build && cd build && ninja install
  register: ass
  when: p.stat.isdir is defined == false
- debug:
    msg: "{{ass}}"


- name: Re-Compiling open5gs
  ansible.builtin.shell: cd /home/vagrant/open5gs && ninja -C build && cd build && ninja install
  register: ass
  when: p.stat.isdir is defined == true
- debug:
    msg: "{{ass}}"
